#include "db_types.h"

const QVector<Type> types = {
    { NoneType, 1, { },                                     { },                                                     { },        { },                                       { },                                                                        { } },
    { Normal,   1, { },                                     { Rock, Steel },                                         { Ghost },  { Fighting },                              { },                                                                        { Ghost } },
    { Fighting, 1, { Normal, Rock, Steel, Ice, Dark },      { Flying, Poison, Bug, Psychic, Fairy },                 { Ghost },  { Flying, Psychic, Fairy },                { Rock, Bug, Dark },                                                        { } },
    { Flying,   1, { Fighting, Bug, Grass },                { Rock, Steel, Electric },                               { },        { Rock, Electric, Ice },                   { Fighting, Bug, Grass },                                                   { Ground } },
    { Poison,   1, { Grass, Fairy },                        { Poison, Ground, Rock, Ghost },                         { Steel },  { Ground, Psychic },                       { Fighting, Poison, Grass, Fairy },                                         { } },
    { Ground,   1, { Poison, Rock, Steel, Fire, Electric }, { Bug, Grass },                                          { Flying }, { Water, Grass, Ice },                     { Poison, Rock },                                                           { Electric } },
    { Rock,     1, { Flying, Bug, Fire, Ice },              { Fighting, Ground, Steel },                             { },        { Fighting, Ground, Steel, Water, Grass }, { Normal, Flying, Poison, Fire },                                           { } },
    { Bug,      1, { Grass, Psychic, Grass },               { Fighting, Flying, Poison, Ghost, Steel, Fire, Fairy }, { },        { Flying, Rock, Fire },                    { Fighting, Ground, Grass },                                                { } },
    { Ghost,    1, { Ghost, Psychic },                      { Dark },                                                { Normal }, { Ghost, Dark },                           { Poison, Bug },                                                            { Normal } },
    { Steel,    2, { Rock, Ice, Fairy },                    { Steel, Fire, Water, Electric },                        { },        { Fighting, Ground, Fire },                { Normal, Flying, Rock, Bug, Steel, Grass, Psychic, Grass, Dragon, Fairy }, { Poison } },
    { Fire,     1, { Bug, Steel, Grass, Ice },              { Rock, Fire, Water, Dragon },                           { },        { Ground, Rock, Water },                   { Bug, Steel, Fire, Grass, Ice, Fairy },                                    { } },
    { Water,    1, { Ground, Rock, Fire },                  { Water, Grass, Dragon },                                { },        { Grass, Electric },                       { Steel, Fire, Water, Ice },                                                { } },
    { Grass,    1, { Ground, Rock, Water },                 { Flying, Poison, Bug, Steel, Fire, Grass, Dragon },     { },        { Flying, Poison, Bug, Fire, Ice },        { Ground, Water, Grass, Electric },                                         { } },
    { Electric, 1, { Flying, Water },                       { Grass, Electric, Dragon },                             { Ground }, { Ground },                                { Flying, Steel, Electric },                                                { } },
    { Psychic,  1, { Fighting, Poison },                    { Steel, Psychic },                                      { Dark },   { Bug, Ghost, Dark },                      { Fighting, Psychic },                                                      { } },
    { Ice,      1, { Flying, Ground, Grass, Dragon },       { Steel, Fire, Water, Ice },                             { },        { Fighting, Rock, Steel, Fire },           { Ice },                                                                    { } },
    { Dragon,   1, { Dragon },                              { Steel },                                               { Fairy },  { Ice, Dragon, Fairy },                    { Fire, Water, Grass, Electric },                                           { } },
    { Dark,     2, { Ghost, Psychic },                      { Fighting, Dark, Fairy },                               { },        { Fighting, Bug, Fairy },                  { Ghost, Dark },                                                            { Psychic } },
    { Fairy,    6, { Fighting, Dragon, Dark },              { Poison, Steel, Fire },                                 { },        { Poison, Steel },                         { Fighting, Bug, Dark },                                                    { Dragon } }
};
